### ISSUE TITLE
AttributeError: 'FieldInfo' object has no attribute 'discriminator'

### ISSUE THREAD

**Issue by baasman** [dagster-io/dagster#14287]
### Dagster version

Version: 1.3.4

### What's the issue?

Simply running Dagster using version 1.3.4 results in the following stack trace:

```
Python 3.9.2 (default, Mar  3 2021, 20:02:32) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dagster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/baasman/miniconda3/envs/pc-pipeline/lib/python3.9/site-packages/dagster/__init__.py", line 473, in <module>
    from dagster._core.storage.fs_io_manager import (
  File "/srv/baasman/miniconda3/envs/pc-pipeline/lib/python3.9/site-packages/dagster/_core/storage/fs_io_manager.py", line 129, in <module>
    config_schema=FilesystemIOManager.to_config_schema(),
  File "/srv/baasman/miniconda3/envs/pc-pipeline/lib/python3.9/site-packages/dagster/_config/pythonic_config/__init__.py", line 281, in to_config_schema
    return DefinitionConfigSchema(infer_schema_from_config_class(cls))
  File "/srv/baasman/miniconda3/envs/pc-pipeline/lib/python3.9/site-packages/dagster/_config/pythonic_config/__init__.py", line 1750, in infer_schema_from_config_class
    fields[pydantic_field.alias] = _convert_pydantic_field(
  File "/srv/baasman/miniconda3/envs/pc-pipeline/lib/python3.9/site-packages/dagster/_config/pythonic_config/__init__.py", line 1494, in _convert_pydantic_field
    if pydantic_field.field_info.discriminator:
AttributeError: 'FieldInfo' object has no attribute 'discriminator'
```

### What did you expect to happen?

I used to be able to import dagster, but after upgrading I'm unable to.

### How to reproduce?

Simply running `dagster --version` causes this error for me.

### Deployment type

Local

### Deployment details

This only occurs when running dagster locally. 

### Additional information

Python==3.9.2

Other packages in environment:
```
absl-py                      1.4.0
aiohttp                      3.8.3
aiosignal                    1.3.1
alembic                      1.6.5
aniso8601                    9.0.1
anyio                        3.6.2
appdirs                      1.4.4
astor                        0.8.1
astroid                      2.5.6
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        22.1.0
backoff                      2.2.1
bcrypt                       4.0.1
black                        19.3b0
blinker                      1.4
blis                         0.7.9
brotlipy                     0.7.0
cachetools                   5.3.0
catalogue                    2.0.7
certifi                      2023.5.7
cffi                         1.15.1
charset-normalizer           2.0.4
click                        8.0.4
cloudpickle                  2.1.0
colorama                     0.4.6
coloredlogs                  14.0
commonmark                   0.9.1
contourpy                    1.0.7
croniter                     1.3.14
cryptography                 39.0.1
cycler                       0.11.0
cymem                        2.0.6
dagit                        1.3.2
dagster                      1.3.4
dagster-postgres             0.19.4
databricks-cli               0.17.6
distlib                      0.3.6
dnspython                    2.3.0
docker                       6.0.1
docopt                       0.6.2
docstring-parser             0.15
entrypoints                  0.4
et-xmlfile                   1.1.0
exceptiongroup               1.1.1
ezml                         1.0.1b3
filelock                     3.12.0
Flask                        2.1.3
flatbuffers                  23.3.3
fonttools                    4.39.4
frozenlist                   1.3.3
fsspec                       2023.4.0
gast                         0.4.0
ghp-import                   2.1.0
gitdb                        4.0.10
github3.py                   4.0.1
GitPython                    3.1.31
google-auth                  2.17.3
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
gql                          3.4.0
graphene                     3.2.2
graphql-core                 3.2.3
graphql-relay                3.2.0
greenlet                     2.0.2
griffe                       0.27.5
grpcio                       1.43.0
grpcio-health-checking       1.47.5
gunicorn                     20.1.0
h11                          0.14.0
h5py                         3.8.0
hdfs                         2.7.0
httptools                    0.5.0
humanfriendly                10.0
idna                         3.4
importlib-metadata           6.6.0
importlib-resources          5.12.0
iniconfig                    2.0.0
isort                        5.8.0
itsdangerous                 2.1.2
jax                          0.4.8
Jinja2                       3.1.2
joblib                       1.2.0
jsonlines                    3.1.0
jsonschema                   4.17.3
keras                        2.12.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
langcodes                    3.3.0
lazy-object-proxy            1.4.3
libclang                     16.0.0
Mako                         1.2.4
Markdown                     3.3.7
markdown-it-py               2.2.0
MarkupSafe                   2.1.2
matplotlib                   3.7.1
mccabe                       0.6.1
mdurl                        0.1.2
mergedeep                    1.3.4
mkdocs                       1.3.1
mkdocs-autorefs              0.4.1
mkdocs-exclude               1.0.2
mkdocs-material              8.2.11
mkdocs-material-extensions   1.1.1
mkdocstrings                 0.19.0
mkdocstrings-python          0.8.3
mkl-fft                      1.3.1
mkl-random                   1.2.2
mkl-service                  2.4.0
ml-dtypes                    0.1.0
mlflow                       1.27.0
msgpack                      1.0.5
multidict                    6.0.4
murmurhash                   1.0.7
mypy-extensions              0.4.3
numpy                        1.23.5
oauthlib                     3.2.2
openpyxl                     3.1.2
opt-einsum                   3.3.0
packaging                    23.0
pandas                       1.5.3
paramiko                     3.1.0
pathy                        0.10.1
pc-pipeline                  0.1         /home/baasman/projects/pc-pipeline
pc-pipeline-dagster          0.0.0       /home/baasman/projects/pc-pipeline/pc_pipeline_dagster
pendulum                     2.1.2
pep562                       1.1
pex                          2.1.134
Pillow                       9.5.0
pip                          23.0.1
platformdirs                 3.5.0
pluggy                       1.0.0
pooch                        1.4.0
preshed                      3.0.6
prometheus-client            0.16.0
prometheus-flask-exporter    0.22.4
prompt-toolkit               3.0.38
protobuf                     3.20.3
psycopg2-binary              2.9.6
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pydantic                     1.10.7
Pygments                     2.11.2
PyJWT                        2.6.0
pylint                       2.8.3
pymdown-extensions           9.3
pymongo                      4.3.3
PyNaCl                       1.5.0
pyOpenSSL                    23.0.0
pyparsing                    3.0.9
pyrsistent                   0.19.3
pysftp                       0.2.8
PySocks                      1.7.1
pytest                       7.3.1
python-dateutil              2.8.2
python-dotenv                1.0.0
python-editor                1.0.4
pytz                         2023.3
pytzdata                     2020.1
PyYAML                       6.0
pyyaml_env_tag               0.1
querystring-parser           1.2.4
questionary                  1.10.0
ray                          1.13.0
regex                        2020.11.13
requests                     2.29.0
requests-oauthlib            1.3.1
requests-toolbelt            0.10.1
rich                         12.6.0
rsa                          4.9
Rx                           1.6.3
scikit-learn                 1.2.2
scipy                        1.9.1
setuptools                   66.0.0
shellingham                  1.5.0.post1
six                          1.16.0
smart-open                   5.2.1
smmap                        5.0.0
sniffio                      1.3.0
spacy                        3.3.1
spacy-legacy                 3.0.12
spacy-loggers                1.0.4
SQLAlchemy                   1.4.47
sqlparse                     0.4.4
srsly                        2.4.6
starlette                    0.26.1
sweetviz                     2.1.4
tabulate                     0.9.0
tensorboard                  2.12.2
tensorboard-data-server      0.7.0
tensorboard-plugin-wit       1.8.1
tensorboardX                 2.6
tensorflow                   2.12.0
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.32.0
termcolor                    2.3.0
thinc                        8.0.15
threadpoolctl                3.1.0
toml                         0.10.2
tomli                        2.0.1
toposort                     1.10
tqdm                         4.65.0
typed-ast                    1.4.2
typer                        0.7.0
typing-compat                0.1.0
typing_extensions            4.5.0
tzdata                       2023.3
universal_pathlib            0.0.23
uritemplate                  4.1.1
urllib3                      1.26.15
uvicorn                      0.22.0
uvloop                       0.17.0
virtualenv                   20.23.0
wasabi                       0.9.1
watchdog                     3.0.0
watchfiles                   0.19.0
wcwidth                      0.2.6
websocket-client             1.5.1
websockets                   11.0.2
Werkzeug                     2.3.1
wheel                        0.38.4
wrapt                        1.12.1
xgboost                      1.6.2
yarl                         1.9.2
zipp                         3.15.0
```

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by baasman** [comment]
Fixed: Downgrading to pydantic 1.10.6 solves this.

**Comment by jorenvs-repr** [comment]
I had the same issue with python 3.9.7. Downgrading pydantic didn't solve. Only thing that worked was creating a clean env using python 3.8.12

**Comment by rexledesma** [comment]
Consolidating in favor of https://github.com/dagster-io/dagster/issues/15162.
