### ISSUE TITLE
Cannot use dagster_pandas.DataFrame input when running on dask

### ISSUE THREAD

**Issue by jack-pace** [dagster-io/dagster#1568]
Running the MWE below gives the following error:
> AttributeError: 'NoneType' object has no attribute 'step_key'

```python
import dask.distributed
from dagster import (
    lambda_solid, pipeline, ExecutionTargetHandle
)
from dagster_dask import execute_on_dask, DaskConfig
import dagster_pandas as dagster_pd


@lambda_solid
def pandas_solid(df: dagster_pd.DataFrame):
    pass


@pipeline
def the_pipeline():
    return pandas_solid()


def test_execute_on_dask(scheduler_port, environment_dict):
    execute_on_dask(
        ExecutionTargetHandle.for_pipeline_python_file(
            __file__, the_pipeline.name
        ),
        env_config={'storage': {'filesystem': {}}, **environment_dict},
        dask_config=DaskConfig(address=f"localhost:{scheduler_port}", timeout=30),
    )


if __name__ == '__main__':
    port = 8786
    with dask.distributed.LocalCluster(scheduler_port=port):
        test_execute_on_dask(
            scheduler_port=port,
            environment_dict={
                'solids': {
                    'pandas_solid': {
                        'inputs': {
                            'df': {
                                'csv': {
                                    'path': 'data/mwe_dask_pandas.csv'
                                }
                            }
                        }
                    }
                }
            }
        )
```
and here is the corresponding csv file `data/mwe_dask_pandas.csv`:
```csv
col_a,col_b
1,xyz
2,pqr
```

**Comment by natekupp** [comment]
Thanks for the report! I've fixed the issue and added a test based on your example here: https://dagster.phacility.com/D639

**Comment by jack-pace** [comment]
Has this been released yet? I've just updated to 0.5.3 but still have the issue :/
