### ISSUE TITLE
Encountering `TemplateNotFound` error on the dbt + Dagster tutorial using a Windows Machine

### ISSUE THREAD

**Issue by Astronaut101** [dagster-io/dagster#15730]
### Dagster version

dagster, version 1.4.4

### What's the issue?

Hello Dagster team 👋 

Our data team is testing the dbt + Dagster integration by working on the dbt + Dagster tutorial documentation provided in your website. Upon running the `dagster-dbt project scaffold --project-name jaffle_dagster` command on the [Using dbt with Dagster, part two: Load dbt models as Dagster Assets](https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/load-dbt-models#using-dbt-with-dagster-part-two-load-dbt-models-as-dagster-assets) section, it successfully created a new `jaffle_dagster` directory inside of the `jaffle_shop` dbt project. However, we have encountered a `TemplateNotFound: scaffold\definitions.py.jinja` error as shown in the error logs below.

```bash
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\dagster_dbt\cli\app.py:189 in project_scaffold_command                                         │
│                                                                                                  │
│   186 │                                                                                          │
│   187 │   dagster_project_dir = Path.cwd().joinpath(project_name)                                │
│   188 │                                                                                          │
│ ❱ 189 │   copy_scaffold(                                                                         │
│   190 │   │   project_name=project_name,                                                         │
│   191 │   │   dagster_project_dir=dagster_project_dir,                                           │
│   192 │   │   dbt_project_dir=dbt_project_dir,                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                          console = <console width=128 ColorSystem.TRUECOLOR>                 │ │
│ │              dagster_project_dir = WindowsPath('C:/Users/Clarence                            │ │
│ │                                    Vinzcent/Data-Engineering-Experimentation/projects/dagst… │ │
│ │                  dbt_project_dir = WindowsPath('C:/Users/Clarence                            │ │
│ │                                    Vinzcent/Data-Engineering-Experimentation/projects/dagst… │ │
│ │                     project_name = 'jaffle_dagster'                                          │ │
│ │ use_dbt_project_package_data_dir = False                                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\dagster_dbt\cli\app.py:119 in copy_scaffold                                                    │
│                                                                                                  │
│   116 │   │   │   destination_path = os.fspath(relative_path.parent.joinpath(relative_path.ste   │
│   117 │   │   │   template_path = os.fspath(path.relative_to(dagster_project_dir))               │
│   118 │   │   │                                                                                  │
│ ❱ 119 │   │   │   env.get_template(template_path).stream(                                        │
│   120 │   │   │   │   dbt_project_dir_relative_path_parts=dbt_project_dir_relative_path_parts,   │
│   121 │   │   │   │   dbt_project_name=dbt_project_name,                                         │
│   122 │   │   │   │   dbt_parse_command=dbt_parse_command,                                       │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                 dagster_project_dir = WindowsPath('C:/Users/Clarence                         │ │
│ │                                       Vinzcent/Data-Engineering-Experimentation/projects/da… │ │
│ │                dbt_adapter_packages = ['dbt-duckdb']                                         │ │
│ │                   dbt_parse_command = ['"parse"']                                            │ │
│ │                   dbt_profiles_path = WindowsPath('C:/Users/Clarence                         │ │
│ │                                       Vinzcent/Data-Engineering-Experimentation/projects/da… │ │
│ │                   dbt_profiles_yaml = {                                                      │ │
│ │                                       │   'jaffle_shop': {                                   │ │
│ │                                       │   │   'target': 'local',                             │ │
│ │                                       │   │   'outputs': {                                   │ │
│ │                                       │   │   │   'local': {                                 │ │
│ │                                       │   │   │   │   'type': 'duckdb',                      │ │
│ │                                       │   │   │   │   'path': 'tutorial.duckdb',             │ │
│ │                                       │   │   │   │   'schema': 'jaffle_shop'                │ │
│ │                                       │   │   │   }                                          │ │
│ │                                       │   │   }                                              │ │
│ │                                       │   }                                                  │ │
│ │                                       }                                                      │ │
│ │                     dbt_project_dir = WindowsPath('C:/Users/Clarence                         │ │
│ │                                       Vinzcent/Data-Engineering-Experimentation/projects/da… │ │
│ │       dbt_project_dir_relative_path = WindowsPath('../..')                                   │ │
│ │ dbt_project_dir_relative_path_parts = ['".."', '".."']                                       │ │
│ │                    dbt_project_name = 'jaffle_shop'                                          │ │
│ │                    dbt_project_yaml = {                                                      │ │
│ │                                       │   'name': 'jaffle_shop',                             │ │
│ │                                       │   'config-version': 2,                               │ │
│ │                                       │   'version': '0.1',                                  │ │
│ │                                       │   'profile': 'jaffle_shop',                          │ │
│ │                                       │   'model-paths': ['models'],                         │ │
│ │                                       │   'seed-paths': ['seeds'],                           │ │
│ │                                       │   'test-paths': ['tests'],                           │ │
│ │                                       │   'analysis-paths': ['analysis'],                    │ │
│ │                                       │   'macro-paths': ['macros'],                         │ │
│ │                                       │   'target-path': 'target',                           │ │
│ │                                       │   ... +3                                             │ │
│ │                                       }                                                      │ │
│ │               dbt_project_yaml_path = WindowsPath('C:/Users/Clarence                         │ │
│ │                                       Vinzcent/Data-Engineering-Experimentation/projects/da… │ │
│ │                    destination_path = 'jaffle_dagster\\scaffold\\definitions.py'             │ │
│ │                                 env = <jinja2.environment.Environment object at              │ │
│ │                                       0x000002499D5475B0>                                    │ │
│ │                                path = WindowsPath('C:/Users/Clarence                         │ │
│ │                                       Vinzcent/Data-Engineering-Experimentation/projects/da… │ │
│ │                        project_name = 'jaffle_dagster'                                       │ │
│ │                       relative_path = WindowsPath('jaffle_dagster/scaffold/definitions.py.j… │ │
│ │                       template_path = 'scaffold\\definitions.py.jinja'                       │ │
│ │    use_dbt_project_package_data_dir = False                                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\jinja2\environment.py:1010 in get_template                                                     │
│                                                                                                  │
│   1007 │   │   if parent is not None:                                                            │
│   1008 │   │   │   name = self.join_path(name, parent)                                           │
│   1009 │   │                                                                                     │
│ ❱ 1010 │   │   return self._load_template(name, globals)                                         │
│   1011 │                                                                                         │
│   1012 │   @internalcode                                                                         │
│   1013 │   def select_template(                                                                  │
│                                                                                                  │
│ ╭──────────────────────────────── locals ─────────────────────────────────╮                      │
│ │ globals = None                                                          │                      │
│ │    name = 'scaffold\\definitions.py.jinja'                              │                      │
│ │  parent = None                                                          │                      │
│ │    self = <jinja2.environment.Environment object at 0x000002499D5475B0> │                      │
│ ╰─────────────────────────────────────────────────────────────────────────╯                      │
│                                                                                                  │
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\jinja2\environment.py:969 in _load_template                                                    │
│                                                                                                  │
│    966 │   │   │   │                                                                             │
│    967 │   │   │   │   return template                                                           │
│    968 │   │                                                                                     │
│ ❱  969 │   │   template = self.loader.load(self, name, self.make_globals(globals))               │
│    970 │   │                                                                                     │
│    971 │   │   if self.cache is not None:                                                        │
│    972 │   │   │   self.cache[cache_key] = template                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ cache_key = (                                                                                │ │
│ │             │   <weakref at 0x000002499EB604A0; to 'FileSystemLoader' at                     │ │
│ │             0x000002499D544AC0>,                                                             │ │
│ │             │   'scaffold\\definitions.py.jinja'                                             │ │
│ │             )                                                                                │ │
│ │   globals = None                                                                             │ │
│ │      name = 'scaffold\\definitions.py.jinja'                                                 │ │
│ │      self = <jinja2.environment.Environment object at 0x000002499D5475B0>                    │ │
│ │  template = None                                                                             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\jinja2\loaders.py:126 in load                                                                  │
│                                                                                                  │
│   123 │   │                                                                                      │
│   124 │   │   # first we try to get the source for this template together                        │
│   125 │   │   # with the filename and the uptodate function.                                     │
│ ❱ 126 │   │   source, filename, uptodate = self.get_source(environment, name)                    │
│   127 │   │                                                                                      │
│   128 │   │   # try to load the code from the bytecode cache if there is a                       │
│   129 │   │   # bytecode cache configured.                                                       │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        code = None                                                                           │ │
│ │ environment = <jinja2.environment.Environment object at 0x000002499D5475B0>                  │ │
│ │     globals = ChainMap({}, {'range': <class 'range'>, 'dict': <class 'dict'>, 'lipsum':      │ │
│ │               <function generate_lorem_ipsum at 0x000002499CE69BD0>, 'cycler': <class        │ │
│ │               'jinja2.utils.Cycler'>, 'joiner': <class 'jinja2.utils.Joiner'>, 'namespace':  │ │
│ │               <class 'jinja2.utils.Namespace'>})                                             │ │
│ │        name = 'scaffold\\definitions.py.jinja'                                               │ │
│ │        self = <jinja2.loaders.FileSystemLoader object at 0x000002499D544AC0>                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\jinja2\loaders.py:195 in get_source                                                            │
│                                                                                                  │
│   192 │   def get_source(                                                                        │
│   193 │   │   self, environment: "Environment", template: str                                    │
│   194 │   ) -> t.Tuple[str, str, t.Callable[[], bool]]:                                          │
│ ❱ 195 │   │   pieces = split_template_path(template)                                             │
│   196 │   │   for searchpath in self.searchpath:                                                 │
│   197 │   │   │   # Use posixpath even on Windows to avoid "drive:" or UNC                       │
│   198 │   │   │   # segments breaking out of the search directory.                               │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ───────────────────────────────────╮                 │
│ │ environment = <jinja2.environment.Environment object at 0x000002499D5475B0>  │                 │
│ │        self = <jinja2.loaders.FileSystemLoader object at 0x000002499D544AC0> │                 │
│ │    template = 'scaffold\\definitions.py.jinja'                               │                 │
│ ╰──────────────────────────────────────────────────────────────────────────────╯                 │
│                                                                                                  │
│ C:\Users\Clarence                                                                                │
│ Vinzcent\Data-Engineering-Experimentation\projects\dagster\dagster_dev_with_bug\lib\site-package │
│ s\jinja2\loaders.py:36 in split_template_path                                                    │
│                                                                                                  │
│    33 │   │   │   or (os.path.altsep and os.path.altsep in piece)                                │
│    34 │   │   │   or piece == os.path.pardir                                                     │
│    35 │   │   ):                                                                                 │
│ ❱  36 │   │   │   raise TemplateNotFound(template)                                               │
│    37 │   │   elif piece and piece != ".":                                                       │
│    38 │   │   │   pieces.append(piece)                                                           │
│    39 │   return pieces                                                                          │
│                                                                                                  │
│ ╭────────────────── locals ───────────────────╮                                                  │
│ │    piece = 'scaffold\\definitions.py.jinja' │                                                  │
│ │   pieces = []                               │                                                  │
│ │ template = 'scaffold\\definitions.py.jinja' │                                                  │
│ ╰─────────────────────────────────────────────╯                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TemplateNotFound: scaffold\definitions.py.jinja
```

This is the result of the created `jaffle_dagster` project directory after encountering the `TemplateNotFound` error.
![Screenshot 2023-08-08 123744](https://github.com/dagster-io/dagster/assets/51937599/3721fbe6-0457-4fbc-a800-a26718bcf6c9)

### What did you expect to happen?

The `dagster-dbt project scaffold --project-name jaffle_dagster` command must be able to locate the `scaffold\definitions.py.jinja` file, but it doesn't convert the jinja template into the expected `definitions.py` file. Also, the `scaffold` directory has not been successfully renamed to `jaffle_dagster` directory. I stepped in through the created project directory by running a Python REPL and inspecting how the `Environment(loader=FileSystemLoader(dagster_project_dir)).list_templates()` is reading its templates, and I noticed that it's looking for forward slashes instead of backward slashes.

```python
>>> from jinja2 import Environment
>>> from jinja2 import FileSystemLoader
>>>
>>> import os
>>> from pathlib import Path
>>>
>>> Path.cwd()
WindowsPath('C:/Users/Clarence Vinzcent/Data-Engineering-Experimentation/projects/dagster/tutorial-dbt-dagster-with-bug/jaffle_shop/jaffle_dagster')    
>>>
>>> dagster_project_dir = Path.cwd()
>>>
>>> env = Environment(loader=FileSystemLoader(dagster_project_dir))
>>> env.list_templates()
['__pycache__/__init__.cpython-310.pyc', 'pyproject.toml', 'scaffold/__init__.py', 'scaffold/__pycache__/__init__.cpython-310.pyc', 'scaffold/definitions.py.jinja', 'setup.py']
```

I applied a temporary workaround into the `dagster-dbt/cli/app.py` under the `copy_scaffold()` function by converting Windows back slashes to forward slashes if it spotted a `definitions.py.jinja` file on one of its search paths.

```python
# dagster-dbt/cli/app.py

def copy_scaffold(
    project_name: str,
    dagster_project_dir: Path,
    dbt_project_dir: Path,
    use_dbt_project_package_data_dir: bool,
) -> None:
    ...

    for path in dagster_project_dir.glob("**/*"):

        if path.suffix == ".jinja":
            relative_path = path.relative_to(Path.cwd())
            destination_path = os.fspath(relative_path.parent.joinpath(relative_path.stem))
            template_path = os.fspath(path.relative_to(dagster_project_dir))

            # NOTE: Temporary workaround
            # ---------------------------------------
            # Updating how Windows slashes from backward slash to forward slash to
            # be properly parsed by the jinja2 template loader. 
            if os.path.basename(path) == 'definitions.py.jinja':
                template_path = 'scaffold/definitions.py.jinja'

            env.get_template(template_path).stream(
                dbt_project_dir_relative_path_parts=dbt_project_dir_relative_path_parts,
                dbt_project_name=dbt_project_name,
                dbt_parse_command=dbt_parse_command,
                dbt_assets_name=f"{dbt_project_name}_dbt_assets",
                dbt_adapter_packages=dbt_adapter_packages,
                project_name=project_name,
                use_dbt_project_package_data_dir=use_dbt_project_package_data_dir,
            ).dump(destination_path)

            path.unlink()

    dagster_project_dir.joinpath("scaffold").rename(dagster_project_dir.joinpath(project_name))

...

```

After applying the aforementioned workaround, it has been able to locate the `scaffold/definitions.py.jinja` template path and I have been able to successfully finish the whole project tutorial. I am not certain if this approach for handling Windows Paths when templates are being read on the `scaffold` directory is the proper way, and I am thinking if the dagster-dbt cli would be able to check what system platform is it using. Then, being able to apply the necessary standard `/` in order for the jinja2 package to read the templates properly. I would love to hear what you guys think on this.

### How to reproduce?

On a Windows Machine, follow the step-by-step tutorial of the [dbt + Dagster integration](https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster#tutorial-using-dbt-with-dagster) up until you reach [Step 2: Create a Dagster project that wraps your dbt project](https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/load-dbt-models#step-2-create-a-dagster-project-that-wraps-your-dbt-project) under the [Part 2 - Load dbt models as assets](https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/load-dbt-models) section.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
Thanks for reporting! This should be resolved in our 1.4.5 release with https://github.com/dagster-io/dagster/pull/15748.

**Comment by Astronaut101** [comment]
Got it, this is great news. 🙌 Thanks @rexledesma!

**Comment by vrajbillings** [comment]
still seeing this on running
```
(dagster38) C:\Users\rajv\dev\tutorial-dbt-dagster>dagster-dbt project scaffold --project-name jaffle_dagster
```
 Is this issue fixed?
```
│ ❱  36 │   │   │   raise TemplateNotFound(template)                                               │
│    37 │   │   elif piece and piece != ".":                                                       │
│    38 │   │   │   pieces.append(piece)                                                           │
│    39 │   return pieces                                                                          │
│                                                                                                  │
│ ╭────────────────── locals ───────────────────╮                                                  │
│ │    piece = 'scaffold\\definitions.py.jinja' │                                                  │
│ │   pieces = []                               │                                                  │
│ │ template = 'scaffold\\definitions.py.jinja' │                                                  │
│ ╰─────────────────────────────────────────────╯                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TemplateNotFound: scaffold\definitions.py.jinja

**Comment by rexledesma** [comment]
@vrajbillings 1.4.5 has not been released yet: https://github.com/dagster-io/dagster/releases. When it is, it will have this fix.
