### ISSUE TITLE
Kill dagit processes more reliably

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1651]
I often get into a state where there are zombie dagit processes (and their child processes) no my machine and they have to be killed. I don't have exact repro instructions but this happens quite a bit.

**Comment by mgasner** [comment]
I think the issue is that killing the watchdog quickly doesn't kill the child process

**Comment by mgasner** [comment]
I think this is resolved? @schrockn

**Comment by schrockn** [comment]
this still happens to me

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
Still?

**Comment by natekupp** [comment]
Closing until we see this again - please reopen if anyone sees this behavior again

**Comment by robhawkes** [comment]
I believe I've had this happen to me today on `0.7.15`. I installed Dagster today and after exiting / Ctrl + C the `dagit` command the Web UI was still available. After looking at the processes I can still see `dagit` and `dagit-cli` running. If I kill those processes the Web UI is unavailable and I can restart the process.
