### ISSUE TITLE
It would be nice if _execute_run_command_body didn't swallow errors

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2515]
These get reported to the instance using `instance.report_engine_event` but don't go back across the ipc channel -- if you call, e.g., ```sync_cli_api_execute_run(
                instance=instance,
                repo_cli_args=ReconstructableRepository.for_file(
                    file_relative_path(__file__, 'file_does_not_exist.py'), 'bar_repo'
                ).get_cli_args(),
                pipeline_name='foo',
                environment_dict={},
                mode='default',
                solid_subset=None,
            )```, this just returns `[]`

**Comment by mgasner** [comment]
related: if you call `sync_cli_api_execute_run` and an error is raised in framework code (e.g. in `execute_run_command`, the sync call hangs until the IPC timeout is hit and then you get ```Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "<stdin>", line 4, in <listcomp>
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/api/execute_run.py", line 35, in sync_cli_api_execute_run
    for message in ipc_read_event_stream(output_file_path):
  File "/Users/max/dev/dagster/python_modules/dagster/dagster/serdes/ipc.py", line 122, in ipc_read_event_stream
    "Timeout: read stream has not received any data in {timeout} seconds"
dagster.serdes.ipc.DagsterIPCProtocolError: Timeout: read stream has not received any data in {timeout} seconds```

**Comment by schrockn** [comment]
This will be resolved with the grpc transition

**Comment by natekupp** [comment]
@gibsondan can you confirm this is fixed now?

**Comment by gibsondan** [comment]
One place where this is decidedly not fixed is in the k8s runs worker execute_run CLI call - If that command raises an exception I think it's reported in the event log but doesn't appear anywhere else, making it pretty difficult to debug errors.

**Comment by gibsondan** [comment]
this is fixed now
