### ISSUE TITLE
kubernetesjsonschema.dev is down

### ISSUE THREAD

**Issue by giautm** [dagster-io/dagster#33134]
### What's the issue?

The site https://kubernetesjsonschema.dev is down, it currently using for schema validation. It blocking our deployment of Dagster, please consider another approach for validation to address this, it also help to install Dagster in Air-gap environment like https://github.com/dagster-io/dagster/issues/29629 mentioned.

Currently, we're trying to workaround with `--skip-schema-validation`

### What did you expect to happen?

No call to third-party domain

### How to reproduce?

Install dagster with latest helm charts.

### Dagster version

any

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Thanks for the report and thanks @kang8 for the fix! That will be included in the next helm chart release. As noted in the original post here, installing with `--skip-schema-validation` will work around the problem with helm installs on existing versions (at the expense of of course no longer validating the JSON against the schema).

**Comment by jieyu-lin** [comment]
@gibsondan we encounter the same issue that all dagster deployments are having the same `dagster-user-deployments: Could not read schema from HTTP, response status is 404 Not Found`, how long can we expect this PR will be rolled out and we may able to restart deployment? Thanks!

**Comment by gibsondan** [comment]
@jieyu-lin will check with the team about exact rollout timing, but is the workaround suggested above of adding `--skip-schema-validation` not working for you?

**Comment by giautm** [comment]
Honestly, I using TF to deploy the helm chart, and it didn't support the flag.

**Comment by ckalla-otto** [comment]
Same here. We are also using terraform and there is no provider supporting `--skip-schema-validation` atm.

**Comment by pat-trunk-io** [comment]
Can this be backported to 1.11.x?
Our company policy is to stay one version behind.

**Comment by gibsondan** [comment]
We just released a 1.12.8 Helm chart release with the community-provided fix - thanks again @kang8 !

**Comment by andrew-ryan-1m** [comment]
Thank you @gibsondan (and everyone else involved) for getting a fix released! 

We're in a similar situation as @pat-trunk-io , and we could benefit from the fix being pushed to older Chart versions, too. 

Asking mostly because we are managing our Helm deployments via Terraform's `helm_release` resource (https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release), which does not yet officially support skipping schema validation (https://github.com/hashicorp/terraform-provider-helm/issues/1609). And it's seeming like we have two options:
1. Post here and cross our fingers that older Chart versions may also get patched somehow
2. Self-host the older Charts for now (in order to remove the `values.schema.json` to disable schema validation) until we can upgrade our Dagster version, etc. to the patched version, at which point we could then switch back to pointing at the Dagster-maintained publicly-hosted Charts. 

Anyone else running into this and finding other work arounds? Thanks everyone!

**Comment by geoHeil** [comment]
one further option might be to use https://fluxcd.io/ with https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ and monkey patch the charts on the fly

**Comment by pat-trunk-io** [comment]
It's a lot to ask us to switch to something like fluxcd for just dagster.

Our team really likes dagster, but there are a lot more stakeholders for the deploy pipelines tooling than for dagster.

We use the CDK helmchart construct and also cannot make it skip verification.

**Comment by jieyu-lin** [comment]
@gibsondan We are using 1.8.x version of dagster as long as we are not plan to upgrade but it is starting failing when new deployment. would you backport to older version like this?

**Comment by sudo-dliberty-eiq** [comment]
We are on version 1.7.8 and seeing this as well.

**Comment by gibsondan** [comment]
There's now a 1.11.16-noschema release at https://artifacthub.io/packages/helm/dagster/dagster with the schema validation removed, for folks who can't use the --skip-schema-validation workaround on 1.11. I was able to run it myself but would somebody using the terraform provider be able to confirm whether it works for them? If that works it may be possible to backport the latest release of some earlier minor versions as well.

**Comment by patricktrainer** [comment]
failing as well on `1.10.5`

**Comment by gibsondan** [comment]
The current workarounds for this are as follows:
- Deploy with the `--skip-schema-validation` flag
- Upgrade your Helm chart to 1.12.8 or higher
- On 1.11.x use the 1.11.16-noschema Helm chart version
- On other versions, you can download the chart file for your desired version here: https://github.com/dagster-io/helm, untar it, remove the values.schema.json, re-tar it, and reference that file locally in your Helm deploy:

```
# 1. Extract the chart
tar -xzf dagster-1.12.7.tgz

# 2. Remove the schemas
rm dagster/values.schema.json
rm dagster/charts/dagster-user-deployments/values.schema.json

# 3. Repackage it (COPYFILE_DISABLE=1 needed on mac)
COPYFILE_DISABLE=1 tar -czf ../dagster-1.12.7-noschema.tgz ./dagster

# 4. Install with it
helm install my-release ./dagster-noschema.1.12.7.tgz
```

**Comment by patricktrainer** [comment]
Thanks @gibsondan

**Comment by jieyu-lin** [comment]
Thanks @gibsondan , we still expect to have schema validation available in older version since back to deployment is important to us in recent day. Upgrading can be another option but we have to investigate that.

**Comment by stevenmurphy12** [comment]
> The current workarounds for this are as follows:
> 
> * Deploy with the `--skip-schema-validation` flag
> * Upgrade your Helm chart to 1.12.8 or higher
> * On 1.11.x use the 1.11.16-noschema Helm chart version
> * On other versions, you can download the chart file for your desired version here: https://github.com/dagster-io/helm, untar it, remove the values.schema.json, re-tar it, and reference that file locally in your Helm deploy:
> 
> ```
> # 1. Extract the chart
> tar -xzf dagster-1.12.7.tgz
> 
> # 2. Remove the schemas
> rm dagster/values.schema.json
> rm dagster/charts/dagster-user-deployments/values.schema.json
> 
> # 3. Repackage it (COPYFILE_DISABLE=1 needed on mac)
> COPYFILE_DISABLE=1 tar -czf ../dagster-1.12.7-noschema.tgz ./dagster
> 
> # 4. Install with it
> helm install my-release ./dagster-noschema.1.12.7.tgz
> ```

Thanks for the info. We're on Dagster `1.10.10` and I used the last option (removing the `.json` files) to get us operational. Didn't want to rush into using the latest version yet.

Adding some more context incase it's helpful to anyone:
- We're using FluxCD
- FluxCD `HelmRepository` was pointing at https://dagster-io.github.io/helm
- I took a copy of `1.10.10` from there, removed the `.json` files, and uploaded it to our internal chart repo.
- I then created a new FluxCD `HelmRepository` pointing to that internal repo, and switched the FluxCD `HelmRelease` to point to that Helm repo instead of the dagster one.

**Comment by aayushighag-acquia** [comment]
Hi,
I am still facing the issue even after trying --skip-schema-validation 

`Error: AdjustmentExecuteError - Kustomize.Execute: Unable to run build.
AdjustmentExecuteError - Kustomize.runCfgGreps: Kustomize build failed with "out:  err: Error: Error: values don't meet the specifications of the schema(s) in the following chart(s):
dagster:
failing loading "https://kubernetesjsonschema.dev/v1.18.0/_definitions.json": HTTP request to https://kubernetesjsonschema.dev/v1.18.0/_definitions.json returned status 404 (Not Found)dagster-user-deployments:
failing loading "https://kubernetesjsonschema.dev/v1.18.0/_definitions.json": HTTP request to https://kubernetesjsonschema.dev/v1.18.0/_definitions.json returned status 404 (Not Found)

".
exit status 1
Usage:
  chandler dependency install [flags]

Flags:
      --debug   Debug flag to leave temp directories
  -h, --help    help for install`

**Comment by gibsondan** [comment]
@aayushighag-acquia The error message that you posted includes the helm command that it tried to run, and that command does not include the --skip-schema-validation flag.

**Comment by aayushighag-acquia** [comment]
@gibsondan This command "chandler dependency install" does not have a --skip-schema-validation flag.
I tried it through helm upgrade --install dagster --skip-schema-validation

**Comment by gibsondan** [comment]
I'm not familiar with chandler - my recommendation would be to try one of the other suggested workarounds if running with --skip-schema-validation is not an option here.

**Comment by g-rutter** [comment]
IMO updating the URL isn't a complete fix and dagster should be able to run with the whole internet inaccessible. I know this has been mentioned before, just want to give it a strong +1

**Comment by GuillermoGarciaF** [comment]
We are experiencing this issue on our internal developer platform. It affects many users, that leverage different Dagster versions. 

The terraform helm command does no support the flag, and we cannot directly use Helm. Forcing everyone to update to latest is not a solution. Manually removing JSON files for each possible Dagster version used is also not an option. We are left with the no-schema chart. Could you please release no-schema charts for all minor versions? 

Ideally we would solve the root cause , instead of disabling schema validation. But I lack enough context to confirm if that’s option, or we depend on external services to fix it.

**Comment by g-rutter** [comment]
Hi @gibsondan has there been any further progress towards ensuring dagster can run with no external resources required from the Internet?

**Comment by L3xooo** [comment]
Hi I added the dagster repository and try to look for version 1.11.6-noschema but the version does not exists. Could you please help me how to install the version as it block out platform during configuration update
`helm search repo dagster/dagster --versions | grep 1.11.6
dagster/dagster                 	1.11.6       	1.11.6     	The data orchestration platform built for produ...
dagster/dagster-user-deployments	1.11.6       	1.11.6     	A chart to deploy code servers for your Dagster...
`

**Comment by gibsondan** [comment]
@L3xooo it should show up if you add `--devel` and search for 1.11.16 instead of 1.11.16:

```
helm search repo dagster/dagster --devel --versions | grep 1.11.16
```

**Comment by ilaikim99** [comment]
The failure is caused by the Helm chart's schema validation referencing an external domain that went down. You can bypass it with a Helm flag, upgrade to a patched chart version, or manually strip the schema file from older charts. You can find the full verified solution at https://cacheoverflow.dev/blog/YM280HUB

**Comment by stigmarl** [comment]
I'm not sure if this is relevant information for this issue. In our setup, we're using the `helm_release` Terraform resource from the `helm` provider, and recently (June) started seeing error messages like below:

```
Error: Error upgrading chart

  with helm_release.dagster_cloud,
  on main.tf line 12, in resource "helm_release" "dagster_cloud":
  12: resource "helm_release" "dagster_cloud" {

Upgrade failed: values don't meet the specifications of the schema(s) in the
following chart(s):
dagster-cloud-agent:
failing loading
"https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.19.0/_definitions.json":
invalid file url:
https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.19.0/_definitions.json
```
I see that the Helm chart schema validation failure was fixed in https://github.com/dagster-io/dagster/pull/33135. Downgrading the helm provider from v3.1.2 to v3.1.1 seems to have fixed the issue on our end, though.

**Comment by gibsondan** [comment]
@stigmarl that looks like a bug with helm that was introduced in 3.18.5 and fixed in 3.18.6, so the terraform provider needs to upgrade the helm version that it’s using: https://github.com/hashicorp/terraform-provider-helm/commit/db1e81e8a1c3621f336a045ae6a8161e736ec312

**Comment by Nerdboard** [comment]
We are still - or again - facing this problem. Using Helm Terraform Provider v3.2 did not fix it for us and terraform still doesnt provide the option to disable the verification. 
So currently our only option seems to be to manually patch the chart.
