### ISSUE TITLE
Upgrade dagster-airflow  to support apache airflow 2.0 

### ISSUE THREAD

**Issue by priye-1** [dagster-io/dagster#4047]
## Use Case
I want to integrate dagster into Airflow by installing Dagster-airflow.  This will enable me to import and manage my Dagster pipelines in airflow.
However, an error occurs after installation because it seems Dagster-Airflow has not been upgraded to support Airflow 2.0 and its dependencies.

## Ideas of Implementation
Upgrade dagster-airflow library

#### Exibit A:
On running `pip check` I get the result:
`apache-airflow 2.0.1 has requirement pendulum~=2.0, but you have pendulum 1.4.4.`

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by schrockn** [comment]
Tracking pendulum here: https://github.com/dagster-io/dagster/issues/4176

**Comment by johnseekins** [comment]
Is there any movement on this? I realize addressing dependency updates is hard, but I can't imagine that @priye-1 and myself are the only people affected by this...

**Comment by sryza** [comment]
@johnseekins - here's a crack at unpinning pendulum in dagster-airflow: https://github.com/dagster-io/dagster/pull/6492. Fingers crossed that it passes tests.

@gibsondan - based on the discussion on https://github.com/dagster-io/dagster/pull/3699, do you foresee any issues with unpinning pendulum in dagster-airflow?

**Comment by gibsondan** [comment]
Yeah I believe that issue has been resolved now!

**Comment by bollwyvl** [comment]
Looks like, even with `pendulum` unpinned, it still doesn't support airflow 2 ([full log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=457244&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=4375)):


```py
export PREFIX=~/tmp/.env
export SRC_DIR=~/tmp/test_tmp
import: 'dagster_airflow'
~/tmp/.env/lib/python3.7/site-packages/airflow/configuration.py:276: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(sqlite3.sqlite_version) < StrictVersion(min_sqlite_version):
Traceback (most recent call last):
  File "~/tmp/test_tmp/run_test.py", line 2, in <module>
    import dagster_airflow
  File "~/tmp/.env/lib/python3.7/site-packages/dagster_airflow/__init__.py", line 10, in <module>
    from .factory import make_airflow_dag, make_airflow_dag_containerized, make_airflow_dag_for_operator
  File "~/tmp/.env/lib/python3.7/site-packages/dagster_airflow/factory.py", line 7, in <module>
    from airflow.operators import BaseOperator
ImportError: cannot import name 'BaseOperator' from 'airflow.operators' (~/tmp/.env/lib/python3.7/site-packages/airflow/operators/__init__.py)
 ```

Looks like that maybe comes from e.g. `from airflow.models.baseoperator import BaseOperator` in airflow 2...
