### ISSUE TITLE
Periodic failures in multiprocessing

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#432]
https://circleci.com/gh/dagster-io/dagster/14979?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

for example

**Comment by freiksenet** [comment]
Should be fixed.

**Comment by schrockn** [comment]
Unfortunately I'm still seeing this.

https://circleci.com/gh/dagster-io/dagster/15389?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by schrockn** [comment]
https://github.com/dagster-io/dagster/tree/flaky-multiprocess-repro

Consistent repro at this branch

**Comment by freiksenet** [comment]
Should be fixed now.
